server:
  port: 9271

spring:
  application:
    name: parking
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/parking?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          druid:
            minIdle: 10
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            maxEvictableIdleTimeMillis: 900000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            break-after-acquire-failure: true
            connection-error-retry-attempts: 0

  servlet:
    multipart:
      max-file-size:  500MB
      max-request-size:  800MB

mybatis-plus:
  # mapper扫描包
  mapper-package: com.rabbiter.**.mapper
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.rabbiter.**.domain
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  token-name: satoken
  timeout: 1800
  activity-timeout: 1800
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false

logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
